# Generated by Django 5.0.7 on 2024-07-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('role1', models.CharField(max_length=50)),
                ('role2', models.CharField(max_length=50, verbose_name='role 2')),
            ],
        ),
    ]
